table Dim_Producto
	excludeFromModelRefresh
	lineageTag: 8d5590c8-701c-4d94-9afe-412a5b955665

	column Product
		dataType: string
		lineageTag: b9f75688-6a65-4681-bece-5a4fdde076ef
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: f740babd-1c37-4e0b-b7a6-730388d8330a
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition Dim_Producto-503b3552-fcb7-4067-a46f-fd5541bf74d0 = m
		mode: import
		queryGroup: Datos
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\vicen\Downloads\DATOS.xlsx"), null, true),
				    SportProducts_Table = Source{[Item="SportProducts",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(SportProducts_Table,{{"Retailer", type text}, {"Retailer ID", Int64.Type}, {"Invoice Date", type date}, {"Region", type text}, {"State", type text}, {"City", type text}, {"Product", type text}, {"Price per Unit", type number}, {"Units Sold", Int64.Type}, {"Total Sales", type number}, {"Operating Profit", type number}, {"Operating Margin", type number}, {"Sales Method", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Product"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

